### PR TITLE
bac-end(topic3.4): added section 3.4 test front end with integration back-end with e2e

### PR DESCRIPTION
**Pull request by muratkeremozcan**

### CODE REVIEW

**Comment by NoriSte** [comment]
Hi @muratkerem! As usual, thank you so much ❤️ Some considerations:
- would you mind creating a totally new section with your chapter? Because
  - the concepts are not completely new to the project (see this [chapter](https://github.com/NoriSte/ui-testing-best-practices/blob/master/sections/testing-strategy/component-vs-integration-vs-e2e-testing.md))
  - I think that the value added by your chapter is a real-case scenario and I think it should be moved to a brand new "Real cases / Siemens" section/chapter, what do you think?
  - and in this case: add the author, this should completely be assigned to you and your own work ❤️
- I changed some external links to the internal counterparts
- I (that's totally subjective) would change the dots that indicated that the UI integration tests don't reach the back-end because I don't think they are perfectly clear. A "stopping" line could be more suitable but, again, it's subjective
- I would add a label to the hardware image (just something like "hardware")

Looking forward to your changes/thoughts 😊

**Comment by NoriSte** [comment]
@jesuswasrasta, feel free to add your own thoughts 😊

**Comment by muratkeremozcan** [comment]
> * would you mind creating a totally new section with your chapter? Because
>   
>   * the concepts are not completely new to the project (see this [chapter](https://github.com/NoriSte/ui-testing-best-practices/blob/master/sections/testing-strategy/component-vs-integration-vs-e2e-testing.md))
>   * I think that the value added by your chapter is a real-case scenario and I think it should be moved to a brand new "Real cases / Siemens" section/chapter, what do you think?
>   * and in this case: add the author, this should completely be assigned to you and your own work ❤️

@NoriSte I was under the impression we were following the [draft.md](https://github.com/NoriSte/ui-testing-best-practices/blob/d242e27601c3b705c2013ea5ff503643881ef042/sections/draft.md) file. Do we not need this section here under [component-vs-integration-vs-e2e-testing.md](https://github.com/NoriSte/ui-testing-best-practices/blob/master/sections/testing-strategy/component-vs-integration-vs-e2e-testing.md) ?  

We can create a new section (Section 5) for Real cases. If we do so, we should check off the section under  [draft.md](https://github.com/NoriSte/ui-testing-best-practices/blob/d242e27601c3b705c2013ea5ff503643881ef042/sections/draft.md) file. 
- [ ] back-end related tests
    - [x] test request and response payloads
    - [ ] **test the frontend with the integration tests, the backend with the E2E one**s
    - [x] test the server schema (or everything that can impact the front-end app like PostMan exports, Elastic Search mappings etc.). That sould not be part of the front-end tests but consider that the app will be often broken by a server data change
    - [x] monitoring tests?

With this information, how would you like to proceed? 

I do not mind the author section, we all contribute.

> * I changed some external links to the internal counterparts
> * I (that's totally subjective) would change the dots that indicated that the UI integration tests don't reach the back-end because I don't think they are perfectly clear. A "stopping" line could be more suitable but, again, it's subjective
> * I would add a label to the hardware image (just something like "hardware")
> 
> Looking forward to your changes/thoughts 😊

I can enhance the image to be more clear.

**Comment by muratkeremozcan** [comment]
@NoriSte The suggested changes have been implemented.

**Comment by NoriSte** [comment]
> @NoriSte I was under the impression we were following the draft.md file. Do we not need this section here under component-vs-integration-vs-e2e-testing.md ?

You're right, the problem is that working alone is different from working together, some stuff was just in my mind and now you're working hard and fast and so I need to be more precise about the work organization. So: sorry if the section list was not perfect, I'll fix it as soon as I can and I come back to you 😊

**Comment by NoriSte** [comment]
@muratkerem I've written even the company name, I think that's could be a big value for the project because it adds context (and makes the examples "real" as advertised) but if you mind, remove it 😉

**Comment by rocketsurgeonboic** [comment]
@NoriSte no problem

**Comment by muratkeremozcan** [comment]
@NoriSte no problem

**Pull request merged**
