### PR TITLE
doc(test-state-pipeline): added sections on test states and pipeline

### PR DESCRIPTION
**Pull request by muratkeremozcan**

### CODE REVIEW

**Comment by NoriSte** [comment]
@anoop-gupt we have a new contributor ❤️ thank you @muratkeremozcan , I'll read it as soon as I can 😊

**Comment by muratkeremozcan** [comment]
@anoop-gupt , are you able to review this one while you are at it? 

Much thanks!

**Comment by muratkeremozcan** [comment]
@NoriSte & @anoop-gupt  This one will need rebasing now that we have section 5 as real life examples.

How would you like to fit this `Advanced: Test States & Test Flake` in? 

I propose making it Section 6.

**Comment by muratkeremozcan** [comment]
@NoriSte & @anoop-gupt  rebased and refined `Section 6 Advanced`

**Comment by NoriSte** [comment]
@muratkerem sorry for the big delay, let me know if my changes are ok for you! Then I can merge your contents 😊

**Comment by muratkeremozcan** [comment]
@NoriSte changes are great, thank you. Please proceed.

**Pull request merged**
